#!/usr/bin/env python3
"""Build source-grounded intake turns from seven training-only pediatric MedSP cases."""
import json
from pathlib import Path

SYSTEM = "Conduct a structured clinical intake interview. Ask one concise, relevant question at a time. Gather relevant history before summarizing. Do not diagnose or prescribe treatment."
CASES = [
('10394/scenario1','My 7-month-old has a fever.','H. Ivan Topee.md',[('When did the fever begin?','It began two days ago.'),('What was the highest temperature you measured?','It reached 104 degrees rectally.'),('How has he been feeding?','He is eating his usual amounts.'),('How many wet diapers has he had?','He has had 6 to 8 wet diapers a day.'),('Has he vomited?','He had two episodes of non-bloody, non-bilious vomiting yesterday.'),('Has he had diarrhea?','No, he has not had diarrhea.'),('Has he had cough or a runny nose?','No, he has not had cough or a runny nose.'),('Has he had any sick contacts or daycare exposure?','He attends daycare but has no known sick contacts.'),('What medicines or allergies does he have?','He takes no medicines and has no known drug allergies.')]),
('10394/scenario2','My toddler has fever and a rash.','I. Abby Cest.md',[('When did the skin problem start?','A bug bite on her left buttock appeared three days ago.'),('How has the area changed?','It has grown with redness and firmness.'),('Have you seen any drainage?','There was yellow drainage today.'),('What temperatures has she had?','She had 101.5 yesterday and 102 today.'),('How has she been drinking?','She has only had two 8-ounce bottles today.'),('How many diapers has she had?','Only two diapers were changed in the past 24 hours.'),('Has she had vomiting or diarrhea?','No, she has not had vomiting or diarrhea.'),('Does she attend daycare?','Yes, she attends daycare with five other children.'),('What medical problems, medicines, or allergies does she have?','She has eczema, uses Aquaphor as needed, and has no known drug allergies.')]),
('10394/scenario3','My 3-week-old stopped breathing and his lips turned blue.','J. Cee Peyare.md',[('What was happening when the episode began?','He was taking a bottle, coughed like he was choking, and spit up a little.'),('What color did his lips turn?','His lips turned blue.'),('How long did it last?','It seemed like a long time, but I do not know exactly how long.'),('What did you do during the episode?','I gave him four rescue breaths and he started breathing again.'),('Did you notice shaking movements?','No, I did not notice shaking of his arms or legs.'),('Has he had fever or cold symptoms?','No, he has not had fever or cold symptoms.'),('How has he been feeding?','He takes his usual 3 to 4 ounces every 3 to 4 hours.'),('Has he had vomiting or spit-up with feeds?','He spits up with about half of his feeds and sometimes seems to choke.'),('Is there relevant family heart history?','His father and older brother had a hole in the heart when young.')]),
('10394/scenario4','My 5-year-old has vomiting and diarrhea.','K. Nora Walk.md',[('When did the diarrhea and vomiting begin?','The diarrhea began two days ago and vomiting started yesterday.'),('Is there blood or mucus in the diarrhea?','No, there is no blood or mucus.'),('What does the vomit look like?','It is non-bilious and non-bloody.'),('How often has this happened?','She has had about 10 episodes of vomiting and diarrhea.'),('Does she have abdominal pain?','Yes, but it feels better after she has diarrhea.'),('How much has she had to drink today?','Only about 4 ounces of liquid.'),('Has she urinated today?','I do not think she has urinated today.'),('Has she had a fever?','Her temperature was 100.4 and improved with Tylenol.'),('Has anyone around her been ill?','Several children in her kindergarten class have been out with diarrhea.')]),
('10394/scenario5','My 9-month-old is wheezing and having trouble breathing.','L. Phyllis Knot.md',[('When did the cough and runny nose start?','They started a couple of days ago and the cough is getting worse.'),('Is the cough affecting sleep?','She is coughing all night and not sleeping well.'),('How has she been feeding?','She is having a hard time eating because of the cough and runny nose.'),('How many wet diapers has she had?','She has had four wet diapers in the last 24 hours.'),('Has she had fever?','Her temperature was 101 and improved with Tylenol.'),('When did you first notice wheezing?','We noticed wheezing today.'),('Does she have vomiting?','Sometimes she coughs so hard that she throws up.'),('Does she attend daycare or have sick contacts?','She does not attend daycare, but family members have cold symptoms.'),('Has she wheezed before or had medical problems?','She has been healthy and has no previous history of wheezing.')]),
('10394/scenario6','My 3-year-old has fever and cough.','M. Ty Kipp Knea.md',[('When did the fever and cough begin?','They began two days ago.'),('What was the highest temperature?','It reached 104.5 degrees.'),('Has medicine helped the fever?','Tylenol and Motrin help a little, but the fever returns.'),('How has he been eating and drinking?','He is not eating as much as normal.'),('How often has he urinated?','He has only gone to the bathroom once in the last 12 hours.'),('Has he vomited or had diarrhea?','No, he has not had vomiting or diarrhea.'),('Have you noticed breathing changes?','He seems to be breathing faster, but I have not heard wheezing.'),('Has he had sick contacts or daycare exposure?','He goes to daycare and his older sister has similar symptoms.'),('What allergies or medicines does he have?','He takes no medicines and has no known drug allergies.')]),
('10394/scenario7','My 3-week-old has a fever.','N. Ty Lee Knoll.md',[('When did you first notice the fever?','I noticed it earlier today.'),('How did you measure the temperature?','We measured it rectally and it was 101 degrees.'),('Has he had cough or congestion?','He has had cough and congestion for three days.'),('How has he been feeding?','He is breastfeeding his normal amounts every three hours.'),('How many wet diapers has he had?','He has had his normal number of wet diapers.'),('Has he had vomiting or diarrhea?','No, he has not had vomiting or diarrhea.'),('Did you give any medicine?','No, we did not give medicine.'),('Has he been unusually fussy?','He has been a little fussier but can be consoled.'),('What medicines or allergies does he have?','He takes Poly-Vi-Sol daily and has no known drug allergies.')]),]
def main():
 root=Path(__file__).resolve().parents[1]; out=root/'processed'/'medsp_pediatric_expansion_v1_train.jsonl'; rows=[]
 for case,opening,file,facts in CASES:
  path=root/'data'/'medsp1000'/'mededportal_10394'/case.split('/')[-1]/'sp_actor'/file; assert path.is_file(),path
  for n,(q,a) in enumerate(facts,1): rows.append({'id':f'mededportal_{case.replace("/","__")}__pediatric_{n:02d}','source_case_id':f'mededportal_{case}','source_quality':'manually authored source-grounded single-turn pair','source_file':f'sp_actor/{file}','messages':[{'role':'system','content':SYSTEM},{'role':'user','content':opening},{'role':'assistant','content':q},{'role':'user','content':a}]})
 assert len(rows)==63 and all(r['messages'][2]['content'].count('?')==1 for r in rows)
 out.write_text(''.join(json.dumps(r)+'\n' for r in rows)); print(f'wrote {len(rows)} records to {out}')
if __name__=='__main__': main()
